name: esdgliderutils
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - pip
  - SQLAlchemy
  - pyodbc
  - pandas

  - pip:
    - dbdreader
    - git+https://github.com/smwoodman/pyglider.git@return-nan
