name: esdgliderutils
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - pip
  - ipykernel #for running things in GCP Jupyter notebooks
  - SQLAlchemy
  - pyodbc
  - numpy
  - pandas
  - xarray
  - scipy

  - pip:
    - dbdreader
    - git+https://github.com/c-proof/pyglider.git@main
    # - git+https://github.com/smwoodman/pyglider.git@return-nan
