name: esdglider
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - pip
  - ipykernel #for running things in GCP Jupyter notebooks  
  - google-crc32c
  - google-cloud-secret-manager

  - SQLAlchemy
  - pyodbc
  - numpy
  - pandas
  - xarray
  - scipy

  - pip:
    - dbdreader
    - git+https://github.com/c-proof/pyglider.git@main

  # After creating and activating conda env, 
  # run the follwoing to install esdglider as editable:
  # `pip install -e ~/glider-utils`
  